// Generated by lazyqmk
// Layout: corne_choc_pro_layout
// Generated: 2026-06-29 18:09:07

#pragma once

// Add keymap-specific configuration here

// Idle Effect Configuration
#define LQMK_IDLE_TIMEOUT_MS 60000
#define LQMK_IDLE_EFFECT_DURATION_MS 300000
#define LQMK_IDLE_EFFECT_MODE RGB_MATRIX_COMMUNITY_MODULE_PALETTEFX_FLOW

// Default to TUI layer-aware RGB colors when available
#ifdef RGB_MATRIX_ENABLE
#    undef RGB_MATRIX_DEFAULT_MODE
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS
#    define LAYER_BASE_COLORS_LAYER_COUNT 7
#endif

// PaletteFX Community Module Configuration
// Note: PaletteFX runs as idle screensaver, not as default mode.
// The idle effect state machine uses LQMK_IDLE_EFFECT_MODE (see above)
// which is set to the PaletteFX default effect at compile time.
#ifdef RGB_MATRIX_ENABLE
#    define PALETTEFX_ENABLE_ALL_EFFECTS
#    define PALETTEFX_ENABLE_ALL_PALETTES
#endif // RGB_MATRIX_ENABLE

// RGB Overlay Ripple Configuration
#define LQMK_RIPPLE_OVERLAY_ENABLED
#define LQMK_RIPPLE_MAX_RIPPLES 4
#define LQMK_RIPPLE_DURATION_MS 500
#define LQMK_RIPPLE_SPEED 200
#define LQMK_RIPPLE_BAND_WIDTH 20
#define LQMK_RIPPLE_AMPLITUDE_PCT 60
#define LQMK_RIPPLE_MAX_RADIUS 4
#define LQMK_RIPPLE_FADE_WIDTH 2
#define LQMK_RIPPLE_SCALED_DURATION 100000UL
#define LQMK_RIPPLE_AMP_SCALE 255
#define LQMK_RIPPLE_TRIGGER_ON_PRESS 1
#define LQMK_RIPPLE_TRIGGER_ON_RELEASE 0
#define LQMK_RIPPLE_WAVE_COUNT 1
#define LQMK_RIPPLE_WAVE_DELAY_MS 400
