// Generated by lazyqmk
// Layout: corne_choc_pro_layout
// Keyboard: keebart/corne_choc_pro/standard
// Layout Variant: LAYOUT_split_3x6_3_ex2

#include QMK_KEYBOARD_H
#include "keymap_extras/keymap_german.h"
#include <lib/lib8tion/lib8tion.h>

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Layer 0: Base
[0] = LAYOUT_split_3x6_3_ex2(
        LCG(KC_Q), KC_Q, LT(3, KC_W), LT(2, KC_E), LT(1, KC_R), LT(6, KC_T), 
        KC_MCTL, KC_TRNS, KC_Z, KC_U, KC_I, KC_O, 
        KC_P, KC_SLSH, KC_ESC, KC_A, LALT_T(KC_S), LCTL_T(KC_D), 
        LSFT_T(KC_F), LGUI_T(KC_G), KC_NO, KC_TRNS, RGUI_T(KC_H), RSFT_T(KC_J), 
        RCTL_T(KC_K), RALT_T(KC_L), KC_MINS, KC_HASH, KC_TRNS, DE_Y, 
        KC_X, KC_C, KC_A, KC_B, KC_N, KC_M, 
        KC_COMM, KC_DOT, KC_LEFT, KC_RGHT, KC_TRNS, LT(4, KC_TAB), 
        KC_BSPC, KC_ENT, KC_SPC, KC_NO
    ),
    // Layer 1: Symbols
[1] = LAYOUT_split_3x6_3_ex2(
        KC_TRNS, KC_TRNS, KC_EXLM, DE_QUES, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, DE_UDIA, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_AMPR, KC_AT, DE_SS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, DE_ODIA, DE_ADIA, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    // Layer 2: Navigation
[2] = LAYOUT_split_3x6_3_ex2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_UP, 
        KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    // Layer 3: Numbers
[3] = LAYOUT_split_3x6_3_ex2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_PMNS, KC_7, KC_8, KC_9, 
        KC_PMNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PPLS, KC_4, 
        KC_5, KC_6, KC_PPLS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PDOT, KC_1, 
        KC_2, KC_3, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_0
    ),
    // Layer 4: Code
[4] = LAYOUT_split_3x6_3_ex2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRC, KC_SLSH, KC_RBRC, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LPRN, 
        KC_QUOT, KC_RPRN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCBR, 
        KC_DQUO, KC_RCBR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    // Layer 5: Mouse
[5] = LAYOUT_split_3x6_3_ex2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    ),
    // Layer 6: Globals
[6] = LAYOUT_split_3x6_3_ex2(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_BRID, KC_BRIU, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MSTP, KC_MPRV, 
        KC_MNXT, KC_MPLY, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, KC_VOLD, 
        KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    )
};

#ifdef ENCODER_MAP_ENABLE
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = {
        ENCODER_CCW_CW(RM_NEXT, RM_PREV),
        ENCODER_CCW_CW(RM_HUEU, RM_HUED),
    },
    [1] = {
        ENCODER_CCW_CW(RM_NEXT, RM_PREV),
        ENCODER_CCW_CW(RM_HUEU, RM_HUED),
    },
    [2] = {
        ENCODER_CCW_CW(RM_NEXT, RM_PREV),
        ENCODER_CCW_CW(RM_HUEU, RM_HUED),
    },
    [3] = {
        ENCODER_CCW_CW(RM_NEXT, RM_PREV),
        ENCODER_CCW_CW(RM_HUEU, RM_HUED),
    },
    [4] = {
        ENCODER_CCW_CW(RM_NEXT, RM_PREV),
        ENCODER_CCW_CW(RM_HUEU, RM_HUED),
    },
    [5] = {
        ENCODER_CCW_CW(RM_NEXT, RM_PREV),
        ENCODER_CCW_CW(RM_HUEU, RM_HUED),
    },
    [6] = {
        ENCODER_CCW_CW(RM_NEXT, RM_PREV),
        ENCODER_CCW_CW(RM_HUEU, RM_HUED),
    },
};
#endif

#ifdef RGB_MATRIX_ENABLE
const uint8_t PROGMEM layer_base_colors[7][46][3] = {
    {
        {220,   0,   0},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        {244,   0, 128},
        { 84,  84,  84},
        {  0, 207, 238},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        {249, 102,   0},
        {  0,  93, 246},
        { 84,  84,  84},
        {249, 102,   0},
        { 84,  84,  84},
        {244,   0, 128},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        {244,   0, 128},
        { 84,  84,  84},
        {  0, 207, 238},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        {  0, 222,  81},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        { 84,  84,  84},
        {  0, 222,  81},
        { 84,  84,  84},
        { 84,  84,  84}
    },
    {
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        {249, 102,   0},
        {123, 204,   0},
        {123, 204,   0},
        {123, 204,   0},
        { 33,  39,  51},
        { 33,  39,  51},
        {123, 204,   0},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        {249, 102,   0},
        { 33,  39,  51},
        {249, 102,   0},
        {249, 102,   0},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51},
        { 33,  39,  51}
    },
    {
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        {219,   0,  97},
        { 51,  51,  51},
        { 51,  51,  51},
        {219,   0,  97},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        {219,   0,  97},
        { 51,  51,  51},
        { 51,  51,  51},
        {219,   0,  97},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51}
    },
    {
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 96, 163,   0},
        { 96, 163,   0},
        { 96, 163,   0},
        {  0, 163,  60},
        {  0, 163,  60},
        {  0, 163,  60},
        { 51,  51,  51},
        {  0, 163,  60},
        {  0, 163,  60},
        {  0, 163,  60},
        {  0, 163,  60},
        {  0, 163,  60},
        {  0, 163,  60},
        {  0, 163,  60},
        { 96, 163,   0},
        { 96, 163,   0},
        { 96, 163,   0},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51}
    },
    {
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        {202, 137,   0},
        {202, 137,   0},
        {202, 137,   0},
        { 51,  51,  51},
        { 51,  51,  51},
        {234,  80,   0},
        {234,  80,   0},
        {234,  80,   0},
        {202, 137,   0},
        {202, 137,   0},
        {202, 137,   0},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51}
    },
    {
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51}
    },
    {
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        {219,   0,  97},
        {  0, 163,  60},
        { 51,  51,  51},
        {202, 137,   0},
        {  0, 163,  60},
        {219,   0,  97},
        { 51,  51,  51},
        { 51,  51,  51},
        {219,   0,  97},
        {  0, 163,  60},
        {202, 137,   0},
        { 51,  51,  51},
        {  0, 163,  60},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51},
        { 51,  51,  51}
    }
};
const uint8_t PROGMEM layer_base_colors_layer_count = 7;
#endif

// Bootloader combo: Q+R (left) or U+P (right) held for 1500ms
static uint32_t bootloader_combo_timer = 0;
static bool bootloader_combo_active = false;

#ifdef RGB_MATRIX_ENABLE
#ifdef LQMK_IDLE_TIMEOUT_MS

// Idle Effect State Machine
typedef enum {
    IDLE_STATE_ACTIVE,
    IDLE_STATE_IDLE_EFFECT,
    IDLE_STATE_OFF
} idle_state_t;

static idle_state_t idle_state = IDLE_STATE_ACTIVE;
static uint32_t last_activity_time = 0;

void matrix_scan_user(void) {
    uint32_t elapsed = timer_elapsed32(last_activity_time);

    switch (idle_state) {
        case IDLE_STATE_ACTIVE:
            if (elapsed >= LQMK_IDLE_TIMEOUT_MS) {
                // Transition to idle effect
                rgb_matrix_mode_noeeprom(LQMK_IDLE_EFFECT_MODE);
                idle_state = IDLE_STATE_IDLE_EFFECT;
            }
            break;

        case IDLE_STATE_IDLE_EFFECT:
            if (elapsed >= LQMK_IDLE_TIMEOUT_MS + LQMK_IDLE_EFFECT_DURATION_MS) {
                // Transition to off
                rgb_matrix_disable_noeeprom();
                idle_state = IDLE_STATE_OFF;
            }
            break;

        case IDLE_STATE_OFF:
            // Stay off until activity
            break;
    }
}

#ifdef LQMK_RIPPLE_OVERLAY_ENABLED
static bool lazyqmk_ripple_trigger(uint16_t keycode, keyrecord_t *record);
#endif

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    bool ripple_triggered = false;
#ifdef LQMK_RIPPLE_OVERLAY_ENABLED
    // Trigger ripple effect on matching key events
    ripple_triggered = lazyqmk_ripple_trigger(keycode, record);
#endif

    // Bootloader combo: Q+R (left) or U+P (right) held for 1500ms
    {
        // Resolve the basic keycode (handle LT/MT/MOD wrappers)
        uint16_t base_kc = keycode;
        if (IS_QK_MODS(keycode)) {
            base_kc = QK_MODS_GET_BASIC_KEYCODE(keycode);
        } else if (IS_QK_LAYER_TAP(keycode)) {
            base_kc = QK_LAYER_TAP_GET_TAP_KEYCODE(keycode);
        } else if (IS_QK_MOD_TAP(keycode)) {
            base_kc = QK_MOD_TAP_GET_TAP_KEYCODE(keycode);
        }
        bool is_combo_key = (base_kc == KC_Q || base_kc == KC_R
                          || base_kc == KC_U || base_kc == KC_P);
        if (is_combo_key) {
            static bool q_held = false;
            static bool r_held = false;
            static bool u_held = false;
            static bool p_held = false;

            if (record->event.pressed) {
                if (base_kc == KC_Q) q_held = true;
                if (base_kc == KC_R) r_held = true;
                if (base_kc == KC_U) u_held = true;
                if (base_kc == KC_P) p_held = true;
            } else {
                if (base_kc == KC_Q) q_held = false;
                if (base_kc == KC_R) r_held = false;
                if (base_kc == KC_U) u_held = false;
                if (base_kc == KC_P) p_held = false;
            }

            // Check if either pair is complete
            bool pair_active = (q_held && r_held) || (u_held && p_held);
            if (pair_active) {
                if (!bootloader_combo_active) {
                    bootloader_combo_timer = timer_read32();
                    bootloader_combo_active = true;
                }
            } else {
                bootloader_combo_active = false;
            }
        }
    }

    if (record->event.pressed || ripple_triggered) {
        // Reset activity timer
        last_activity_time = timer_read32();

        if (idle_state != IDLE_STATE_ACTIVE) {
            // Re-enable RGB if it was disabled
            if (idle_state == IDLE_STATE_OFF) {
                rgb_matrix_enable_noeeprom();
            }

            // Restore TUI layer colors mode
            rgb_matrix_mode_noeeprom(RGB_MATRIX_TUI_LAYER_COLORS);
            idle_state = IDLE_STATE_ACTIVE;
        }
    }

    return true;
}

void keyboard_post_init_user(void) {
    last_activity_time = timer_read32();
}

#endif // LQMK_IDLE_TIMEOUT_MS
#endif // RGB_MATRIX_ENABLE

#ifdef RGB_MATRIX_ENABLE
#ifdef LQMK_RIPPLE_OVERLAY_ENABLED

// Reactive key-action overlay (custom implementation)
// Expanding wavefront ring, additive on TUI colors, per-key color.

// Forward declaration from QMK (used for per-key layer resolution)
uint8_t layer_switch_get_layer(keypos_t key);

typedef struct {
    uint8_t led_index;
    uint8_t row;
    uint8_t col;
    uint32_t start_time;
    uint32_t trigger_delay_ms;
    bool active;
} ripple_t;

static ripple_t ripples[LQMK_RIPPLE_MAX_RIPPLES] = {0};

static void lazyqmk_ripple_add(uint8_t led_index, uint8_t row, uint8_t col, uint32_t delay_ms) {
    // Find an empty slot or the oldest ripple
    uint8_t oldest_idx = 0;
    uint32_t oldest_time = ripples[0].start_time;

    for (uint8_t i = 0; i < LQMK_RIPPLE_MAX_RIPPLES; i++) {
        if (!ripples[i].active) {
            ripples[i].led_index = led_index;
            ripples[i].row = row;
            ripples[i].col = col;
            ripples[i].start_time = timer_read32();
            ripples[i].trigger_delay_ms = delay_ms;
            ripples[i].active = true;
            return;
        }
        if (ripples[i].start_time < oldest_time) {
            oldest_time = ripples[i].start_time;
            oldest_idx = i;
        }
    }

    // Replace oldest if no empty slot
    ripples[oldest_idx].led_index = led_index;
    ripples[oldest_idx].row = row;
    ripples[oldest_idx].col = col;
    ripples[oldest_idx].start_time = timer_read32();
    ripples[oldest_idx].trigger_delay_ms = delay_ms;
    ripples[oldest_idx].active = true;
}

static uint8_t lazyqmk_matrix_to_led(uint8_t row, uint8_t col) {
    for (uint8_t i = 0; i < RGB_MATRIX_LED_COUNT; i++) {
        if (g_led_config.matrix_co[row][col] == i) {
            return i;
        }
    }
    // Fallback to center LED if mapping not found
    return RGB_MATRIX_LED_COUNT / 2;
}

// LED index -> matrix position mapping (for per-key layer resolution)
const uint8_t PROGMEM lazyqmk_led_to_matrix_row[46] = { 3, 2, 1, 0, 0, 1, 2, 3, 3, 2, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 0, 1, 7, 6, 5, 4, 4, 5, 6, 7, 7, 6, 5, 4, 4, 5, 6, 6, 5, 4, 4, 5, 6, 4, 5 };
const uint8_t PROGMEM lazyqmk_led_to_matrix_col[46] = { 5, 5, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 1, 1, 1, 0, 0, 0, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 1, 1, 1, 0, 0, 0, 6, 6 };

static RGB lazyqmk_ripple_base_color(uint8_t led_index) {
    RGB color = {0, 0, 0};

#ifdef LAYER_BASE_COLORS_LAYER_COUNT
    uint8_t row = pgm_read_byte(&lazyqmk_led_to_matrix_row[led_index]);
    uint8_t col = pgm_read_byte(&lazyqmk_led_to_matrix_col[led_index]);
    keypos_t key = { .row = row, .col = col };
    uint8_t layer = layer_switch_get_layer(key);
    if (layer < layer_base_colors_layer_count) {
        color.r = pgm_read_byte(&layer_base_colors[layer][led_index][0]);
        color.g = pgm_read_byte(&layer_base_colors[layer][led_index][1]);
        color.b = pgm_read_byte(&layer_base_colors[layer][led_index][2]);
        return color;
    }
#endif

    rgb_t matrix_rgb = hsv_to_rgb(rgb_matrix_get_hsv());
    color.r = matrix_rgb.r;
    color.g = matrix_rgb.g;
    color.b = matrix_rgb.b;
    return color;
}

static void lazyqmk_reactive_apply(uint8_t led_index) {
    uint32_t now = timer_read32();
    // Accumulate color contribution from each ripple in range.
    uint8_t contrib_r = 0, contrib_g = 0, contrib_b = 0;

    for (uint8_t i = 0; i < LQMK_RIPPLE_MAX_RIPPLES; i++) {
        if (!ripples[i].active) continue;

        uint32_t elapsed_ms = now - ripples[i].start_time;
        // Respect trigger delay for multi-wave cascading
        if (elapsed_ms < ripples[i].trigger_delay_ms) continue;
        uint32_t effective_elapsed = elapsed_ms - ripples[i].trigger_delay_ms;
        if (effective_elapsed >= LQMK_RIPPLE_DURATION_MS) {
            ripples[i].active = false;
            continue;
        }

        uint32_t scaled = (uint32_t)effective_elapsed * LQMK_RIPPLE_MAX_RADIUS * LQMK_RIPPLE_SPEED;
        uint8_t radius = (uint8_t)(scaled / LQMK_RIPPLE_SCALED_DURATION);
        // Intensity envelope: triangle ramp 0→255→0 over duration
        uint8_t amp = (uint8_t)scale16by8(
            effective_elapsed < (LQMK_RIPPLE_DURATION_MS / 2)
                ? (uint16_t)(effective_elapsed * 2)
                : (uint16_t)((LQMK_RIPPLE_DURATION_MS - effective_elapsed) * 2),
            LQMK_RIPPLE_AMP_SCALE);

        // Compute distance using MATRIX positions
        uint8_t led_row = pgm_read_byte(&lazyqmk_led_to_matrix_row[led_index]);
        uint8_t led_col = pgm_read_byte(&lazyqmk_led_to_matrix_col[led_index]);
        int8_t drow = (int8_t)led_row - (int8_t)ripples[i].row;
        int8_t dcol = (int8_t)led_col - (int8_t)ripples[i].col;
        if (drow < 0) drow = -drow;
        if (dcol < 0) dcol = -dcol;

        // Skip if outside the maximum ring area
        if (drow > LQMK_RIPPLE_MAX_RADIUS + 1 || dcol > LQMK_RIPPLE_MAX_RADIUS + 1) continue;
        uint8_t dist = (uint8_t)(drow + dcol);

        uint8_t bump;
        if (dist <= radius) {
            // Inside the wavefront: gradient fading toward center
            uint8_t inner_dist = radius - dist;
            if (inner_dist > LQMK_RIPPLE_FADE_WIDTH) continue;
            bump = scale8((uint8_t)(255 - 255 * inner_dist / LQMK_RIPPLE_FADE_WIDTH), amp);
        } else {
            // Outside the wavefront: gradient fading outward
            uint8_t outer_dist = dist - radius;
            if (outer_dist > LQMK_RIPPLE_FADE_WIDTH) continue;
            bump = scale8((uint8_t)(255 - 255 * outer_dist / LQMK_RIPPLE_FADE_WIDTH), amp);
        }
        if (bump == 0) continue;

        {
            RGB c = lazyqmk_ripple_base_color(ripples[i].led_index);
            contrib_r = qadd8(contrib_r, scale8(c.r, bump));
            contrib_g = qadd8(contrib_g, scale8(c.g, bump));
            contrib_b = qadd8(contrib_b, scale8(c.b, bump));
        }
    }

    // Nothing to render
    if (contrib_r == 0 && contrib_g == 0 && contrib_b == 0) return;

    // Read the TUI base color for the current LED
    RGB base = lazyqmk_ripple_base_color(led_index);
    // Additive contribution (multi-ripple aware)
    base.r = qadd8(base.r, contrib_r);
    base.g = qadd8(base.g, contrib_g);
    base.b = qadd8(base.b, contrib_b);
    rgb_matrix_set_color(led_index, base.r, base.g, base.b);
}

static bool lazyqmk_ripple_trigger(uint16_t keycode, keyrecord_t *record) {
    if (keycode == KC_TRNS) return false;
    if (IS_MODIFIER_KEYCODE(keycode)) return false;
    // Get LED index from matrix position
    uint8_t led_index = lazyqmk_matrix_to_led(record->event.key.row, record->event.key.col);

    bool should_trigger = false;
    if (record->event.pressed && LQMK_RIPPLE_TRIGGER_ON_PRESS) should_trigger = true;
    if (should_trigger) {
        // Spawn concentric waves with staggered delays
        for (uint8_t w = 0; w < LQMK_RIPPLE_WAVE_COUNT; w++) {
            lazyqmk_ripple_add(led_index, record->event.key.row, record->event.key.col,
                               (uint32_t)w * LQMK_RIPPLE_WAVE_DELAY_MS);
        }
        return true;
    }
    return false;
}

bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    for (uint8_t i = led_min; i < led_max; i++) {
        lazyqmk_reactive_apply(i);
    }
    return false;
}

#endif // LQMK_RIPPLE_OVERLAY_ENABLED
#endif // RGB_MATRIX_ENABLE


// Bootloader combo: check timer in housekeeping task
void housekeeping_task_user(void) {
    if (bootloader_combo_active && timer_elapsed32(bootloader_combo_timer) > 1500) {
        bootloader_jump();
    }
}
